# Generated by Django 5.0.7 on 2024-09-18 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=45, null=True)),
                ('accords', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.CharField(blank=True, max_length=45, null=True)),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
                ('daynight', models.CharField(blank=True, max_length=45, null=True)),
                ('longevity', models.IntegerField(blank=True, null=True)),
                ('sillage', models.IntegerField(blank=True, null=True)),
                ('top', models.CharField(blank=True, max_length=200, null=True)),
                ('middle', models.CharField(blank=True, max_length=200, null=True)),
                ('base', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('votes', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
