# Generated by Django 5.0.7 on 2024-09-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_perfume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='base',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='middle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='top',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
