# Generated by Django 5.0.7 on 2024-09-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_perfume_base_alter_perfume_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='top',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
