# Generated by Django 5.0.7 on 2024-09-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_perfume_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
