# Generated by Django 5.0.7 on 2024-09-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_perfume_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
