# Generated by Django 5.0.7 on 2024-09-21 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='votes',
            new_name='numReviews',
        ),
    ]
